### ISSUE TITLE
atime, ctime, mtime

### ISSUE THREAD

**Issue by ZinuoCai** [2019SE419/CSEReviewNote#3]
我查了网上的资料，似乎对3个time更准确的解释：
- atime(access time) can be changed by `READ`.
- mtime(modification time) can be changed by `WRITE`.
- ctime(change time): when the inode of file changed, e.g. size, permission, owner and so on, ctime will change,too. So if mtime changes, ctime must change.

**Comment by tx19980520** [comment]
都没想到会有人提issue，这个地方确实是这样，你提个PR merge进来吧

**Comment by Gusabary** [comment]
nb啊 czn
